import sqlalchemy
db = "postgresql://ruslan:ru13aaogh06(@localhost:5432/dbhomework"
engine = sqlalchemy.create_engine(db)
connection = engine.connect()
# performers
# connection.execute("""INSERT INTO performers(id, name)
#             VALUES(1,'Макс Корж')
# """)
# connection.execute("""INSERT INTO performers(id, name)
#             VALUES(2,'Miyagi')
# """)
# connection.execute("""INSERT INTO performers(id, name)
#             VALUES(3,'Juice WRLD')
# """)
# connection.execute("""INSERT INTO performers(id, name)
#             VALUES(4,'XXXTENTACION')
# """)
# connection.execute("""INSERT INTO performers(id, name)
#             VALUES(5,'Rammstein')
# """)
# connection.execute("""INSERT INTO performers(id, name)
#             VALUES(6,'Цой')
# """)
# connection.execute("""INSERT INTO performers(id, name)
#             VALUES(7,'Егор Крид')
# """)
# connection.execute("""INSERT INTO performers(id, name)
#             VALUES(8,'Feduk')
# """)
#genre
# connection.execute("""INSERT INTO genre(id, name)
#             VALUES(1, 'pop')
# """)
# connection.execute("""INSERT INTO genre(id, name)
#             VALUES(2, 'rok')
# """)
# connection.execute("""INSERT INTO genre(id, name)
#             VALUES(3, 'metal')
# """)
# connection.execute("""INSERT INTO genre(id, name)
#             VALUES(4, 'hip-hop')
# """)
# connection.execute("""INSERT INTO genre(id, name)
#             VALUES(5, 'rap')
# """)
# performe_genre
# connection.execute("""INSERT INTO performe_genre(author_id, genre_id)
#             VALUES(1, 4)
# """)
# connection.execute("""INSERT INTO performe_genre(author_id, genre_id)
#             VALUES(2, 4)
# """)
# connection.execute("""INSERT INTO performe_genre(author_id, genre_id)
#             VALUES(3, 5)
# """)
# connection.execute("""INSERT INTO performe_genre(author_id, genre_id)
#             VALUES(4, 5)
# """)
# connection.execute("""INSERT INTO performe_genre(author_id, genre_id)
#             VALUES(5, 3)
# """)
# connection.execute("""INSERT INTO performe_genre(author_id, genre_id)
#             VALUES(6, 2)
# """)
# connection.execute("""INSERT INTO performe_genre(author_id, genre_id)
#             VALUES(7, 1)
# """)
# connection.execute("""INSERT INTO performe_genre(author_id, genre_id)
#             VALUES(8, 1)
# """)
#albums
# connection.execute("""INSERT INTO albums(id, name, year_of_issue)
#             VALUES(1, 'Малый повзраслел', 2017)
# """)
# connection.execute("""INSERT INTO albums(id, name, year_of_issue)
#             VALUES(2, '2 типа людей', 2019)
# """)
# connection.execute("""INSERT INTO albums(id, name, year_of_issue)
#             VALUES(3, 'I got love', 2016)
# """)
# connection.execute("""INSERT INTO albums(id, name, year_of_issue)
#             VALUES(4, 'YAMAKASI', 2020)
# """)
# connection.execute("""INSERT INTO albums(id, name, year_of_issue)
#             VALUES(5, 'Bandit', 2019)
# """)
# connection.execute("""INSERT INTO albums(id, name, year_of_issue)
#             VALUES(6, 'Hate me', 2019)
# """)
# connection.execute("""INSERT INTO albums(id, name, year_of_issue)
#             VALUES(7, 'Look At Me!', 2017)
# """)
# connection.execute("""INSERT INTO albums(id, name, year_of_issue)
#             VALUES(8, 'HEARTEATER', 2019)
# """)
# connection.execute("""INSERT INTO albums(id, name, year_of_issue)
#             VALUES(9, 'DEUTSHLAND', 2019)
# """)
# connection.execute("""INSERT INTO albums(id, name, year_of_issue)
#             VALUES(10, 'ode to Rammstein', 2013)
# """)
# connection.execute("""INSERT INTO albums(id, name, year_of_issue)
#             VALUES(11, 'Ленинград', 1984 )
# """)
# connection.execute("""INSERT INTO albums(id, name, year_of_issue)
#             VALUES(12, 'Будильник', 2015 )
# """)
# connection.execute("""INSERT INTO albums(id, name, year_of_issue)
#             VALUES(13, '58', 2020 )
# """)
# connection.execute("""INSERT INTO albums(id, name, year_of_issue)
#             VALUES(14, '27', 2019 )
# """)
# connection.execute("""INSERT INTO albums(id, name, year_of_issue)
#             VALUES(15, 'Холостяк', 2018 )
# """)
# connection.execute("""INSERT INTO collection(id, name, year_of_issue)
#             VALUES(1, 'rok songs', 2018)
# """)
# connection.execute("""INSERT INTO collection(id, name, year_of_issue)
#             VALUES(2, 'pop songs', 2018)
# """)
# connection.execute("""INSERT INTO collection(id, name, year_of_issue)
#             VALUES(3, 'metal songs', 2021)
# """)
# connection.execute("""INSERT INTO collection(id, name, year_of_issue)
#             VALUES(4, 'hip-hop songs', 2019)
# """)
# connection.execute("""INSERT INTO collection(id, name, year_of_issue)
#             VALUES(5, 'rap songs', 2013)
# """)
# connection.execute("""INSERT INTO performers_album(album_id, author_id)
#             VALUES(1, 1)
# """)
# connection.execute("""INSERT INTO performers_album(album_id, author_id)
#             VALUES(2, 1)
# """)
# connection.execute("""INSERT INTO performers_album(album_id, author_id)
#             VALUES(3, 2)
# """)
# connection.execute("""INSERT INTO performers_album(album_id, author_id)
#             VALUES(4, 2)
# """)
# connection.execute("""INSERT INTO performers_album(album_id, author_id)
#             VALUES(5, 3)
# """)
# connection.execute("""INSERT INTO performers_album(album_id, author_id)
#             VALUES(6, 3)
# """)
# connection.execute("""INSERT INTO performers_album(album_id, author_id)
#             VALUES(7, 4)
# """)
# connection.execute("""INSERT INTO performers_album(album_id, author_id)
#             VALUES(8, 4)
# """)
# connection.execute("""INSERT INTO performers_album(album_id, author_id)
#             VALUES(9, 5)
# """)
# connection.execute("""INSERT INTO performers_album(album_id, author_id)
#             VALUES(10, 5 )
# """)
# connection.execute("""INSERT INTO performers_album(album_id, author_id)
#             VALUES(11, 6)
# """)
# connection.execute("""INSERT INTO performers_album(album_id, author_id)
#             VALUES(12, 7)
# """)
# connection.execute("""INSERT INTO performers_album(album_id, author_id)
#             VALUES(13, 7)
# """)
# connection.execute("""INSERT INTO performers_album(album_id, author_id)
#             VALUES(14, 8)
# """)
# connection.execute("""INSERT INTO performers_album(album_id, author_id)
#             VALUES(15, 8)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(1, 'малиновый закат', 3, 1)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(2, 'оптимист', 3.25, 1)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(3, '2 типа людей', 4.25, 2)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(4, 'i got love', 4.5, 3)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(5, 'minor', 3, 4)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(6, 'my bandit', 3, 5)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(7, 'hate me' ,3 ,6)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(8, 'look at me!', 2, 7)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(9, 'hearteater', 2, 8)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(10, 'deutschland', 5, 9)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(11, 'ode to rammstein', 3, 10)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(12, 'восьмиклассница', 3.5, 11)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(13, 'лето', 2.5, 11)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(14, 'будильник', 3.5, 12)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(15, '58', 2 ,13)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(16, 'веселая песня', 3, 13)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(17, '27', 2.5, 14)
# """)
# connection.execute("""INSERT INTO songs(id, name, duration, albumid)
#             VALUES(18, 'холостяк', 3, 15)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(1, 4)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(2, 4)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(3, 4)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(4, 4)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(5, 4)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(6, 5)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(7, 5)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(8, 5)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(9, 5)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(10, 3)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(11, 3)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(12, 1)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(13, 1)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(14, 2)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(15, 2)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(16, 2)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(17, 2)
# """)
# connection.execute("""INSERT INTO coll_of_songs(song_id, coll_id)
#             VALUES(18, 2)
# """)



